import { describe, it, expect } from 'vitest'
import {
  CODEX_MECHANICS,
  type CodexChapter,
  type CodexTopic,
} from '../src/content/codex'
import { BUILDINGS, BUILDING_IDS } from '../src/content/buildings'
import { UNITS, UNIT_IDS } from '../src/content/units'
import { TECH_NODE_IDS } from '../src/content/tech'
import { PRESTIGE_NODE_IDS } from '../src/content/prestige'
import { ACHIEVEMENT_IDS } from '../src/content/achievements'
import { RESOURCE_IDS } from '../src/engine/state'

/**
 * M6.3 — Codex (kodeks): a READ-ONLY in-game encyclopaedia.
 *
 * Most Codex sections (resources / buildings / units / tree / prestige / achievements)
 * are GENERATED by the panel straight from the existing content tables, so they need no
 * prose of their own. The one thing that cannot be derived — the human-readable
 * explanation of the game's MECHANICS — lives as DATA in content/codex.ts
 * (CODEX_MECHANICS). This file is a pure-data leaf (imports nothing), so the test stays
 * fully deterministic: no engine state, no RNG, no DOM.
 *
 * What is pinned here:
 *  - the CODEX_MECHANICS catalogue is well-formed (non-empty chapters, every chapter
 *    carries a title and at least one topic, every topic a title and at least one
 *    non-empty paragraph) and stable (all ids unique and slug-shaped for anchors);
 *  - the contract-guaranteed mechanics topics are present (combat / raids+wall /
 *    siege+scout), so the key systems are always documented even as the chapter set
 *    grows wider;
 *  - the content tables the panel iterates exist and have no dangling ids — the panel
 *    walks BUILDING_IDS / UNIT_IDS and looks each up in BUILDINGS / UNITS, so a missing
 *    entry would crash the read-only view.
 */

/** A valid anchor/key slug: lowercase letters, digits and hyphens only. */
const SLUG = /^[a-z0-9-]+$/

/** Flatten every topic in chapter order, keeping a reference to its parent chapter. */
function allTopics(): Array<{ chapter: CodexChapter; topic: CodexTopic }> {
  return CODEX_MECHANICS.flatMap((chapter) =>
    chapter.topics.map((topic) => ({ chapter, topic })),
  )
}

describe('CODEX_MECHANICS — catalogue integrity', () => {
  it('is a non-empty list of chapters', () => {
    expect(Array.isArray(CODEX_MECHANICS)).toBe(true)
    expect(CODEX_MECHANICS.length).toBeGreaterThan(0)
  })

  it('every chapter has a non-empty id, title and at least one topic', () => {
    for (const chapter of CODEX_MECHANICS) {
      expect(typeof chapter.id).toBe('string')
      expect(chapter.id.trim().length).toBeGreaterThan(0)
      expect(typeof chapter.title).toBe('string')
      expect(chapter.title.trim().length).toBeGreaterThan(0)
      expect(Array.isArray(chapter.topics)).toBe(true)
      expect(chapter.topics.length).toBeGreaterThan(0)
    }
  })

  it('every topic has a non-empty id, title and at least one non-empty paragraph', () => {
    for (const { chapter, topic } of allTopics()) {
      const where = `${chapter.id}/${topic.id}`
      expect(typeof topic.id, where).toBe('string')
      expect(topic.id.trim().length, where).toBeGreaterThan(0)
      expect(typeof topic.title, where).toBe('string')
      expect(topic.title.trim().length, where).toBeGreaterThan(0)
      expect(Array.isArray(topic.body), where).toBe(true)
      expect(topic.body.length, where).toBeGreaterThan(0)
      for (const paragraph of topic.body) {
        expect(typeof paragraph, where).toBe('string')
        expect(paragraph.trim().length, where).toBeGreaterThan(0)
      }
    }
  })

  it('all ids (chapters and topics) are globally unique', () => {
    const ids = [
      ...CODEX_MECHANICS.map((c) => c.id),
      ...allTopics().map(({ topic }) => topic.id),
    ]
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('all ids are valid anchor slugs (lowercase / digits / hyphen)', () => {
    expect(CODEX_MECHANICS.every((c) => SLUG.test(c.id))).toBe(true)
    expect(allTopics().every(({ topic }) => SLUG.test(topic.id))).toBe(true)
  })
})

describe('CODEX_MECHANICS — guaranteed mechanics coverage', () => {
  // The contract guarantees these chapters/topics document the core combat systems.
  // Subset checks: the catalogue may grow wider, but these must never disappear.
  const REQUIRED: Record<string, readonly string[]> = {
    walka: ['moc-armii', 'rozstrzygniecie', 'szczescie'],
    'najazdy-obrona': ['najazdy', 'mur'],
    'oblezenie-zwiad': ['zwiad', 'taran', 'katapulta'],
  }

  it('contains every required chapter with its required topics', () => {
    const byId = new Map(CODEX_MECHANICS.map((c) => [c.id, c]))
    for (const [chapterId, topicIds] of Object.entries(REQUIRED)) {
      const chapter = byId.get(chapterId)
      expect(chapter, `missing chapter '${chapterId}'`).toBeDefined()
      const have = new Set(chapter!.topics.map((t) => t.id))
      for (const topicId of topicIds) {
        expect(have.has(topicId), `missing topic '${chapterId}/${topicId}'`).toBe(true)
      }
    }
  })
})

describe('Codex content sources — panel has data and no dangling ids', () => {
  it('every catalogue the panel iterates is non-empty', () => {
    expect(RESOURCE_IDS.length).toBeGreaterThan(0)
    expect(BUILDING_IDS.length).toBeGreaterThan(0)
    expect(UNIT_IDS.length).toBeGreaterThan(0)
    expect(TECH_NODE_IDS.length).toBeGreaterThan(0)
    expect(PRESTIGE_NODE_IDS.length).toBeGreaterThan(0)
    expect(ACHIEVEMENT_IDS.length).toBeGreaterThan(0)
  })

  it('every building id resolves to a definition with the matching id', () => {
    for (const id of BUILDING_IDS) {
      const def = BUILDINGS[id]
      expect(def, `building '${id}'`).toBeDefined()
      expect(def.id).toBe(id)
    }
  })

  it('every unit id resolves to a definition with the matching id', () => {
    for (const id of UNIT_IDS) {
      const def = UNITS[id]
      expect(def, `unit '${id}'`).toBeDefined()
      expect(def.id).toBe(id)
    }
  })
})
