/**
 * Codex (kodeks) catalogue — PURE DATA (no engine logic lives here).
 *
 * The Codex tab (M6.3) is a READ-ONLY, in-game encyclopaedia. Most of its sections
 * (buildings / units / tree / prestige / achievements / resources) are GENERATED by
 * the panel (src/ui/panels/codex.ts) straight from the existing content modules
 * (content/buildings.ts, content/units.ts, content/tech.ts, …) — never duplicated
 * here. This file owns only the one thing that cannot be derived from those tables:
 * the human-readable explanation of the game's MECHANICS (how combat, raids, sieges,
 * scouting, conquest, the tree, prestige, automation and offline progress actually
 * work), authored as DATA so the panel can render it without holding any prose.
 *
 * The descriptions are PL and TRUE to the code: every figure cited here is taken from
 * the live constants (combat.ts COMBAT_LUCK / RAM_DEF_RED / CATA_PER_LEVEL,
 * raids.ts RAID_* knobs, conquest.ts LOYALTY_*, offline.ts MAX_OFFLINE_SECONDS, …),
 * so the encyclopaedia never drifts from the simulation. When a mechanic is
 * rebalanced, its topic text here is updated in the same edit.
 *
 * Import discipline: this module imports NOTHING (it is pure text data), so it can
 * never form an initialisation cycle (mirrors the other content/* leaves). It is a
 * leaf consumed only by the Codex panel and its test.
 *
 * SHAPE (the contract): the two interfaces below plus the {@link CODEX_MECHANICS}
 * export. THIS FILE now carries the FULL set of mechanics chapters — economy,
 * combat, raids/defence, siege/scouting, conquest, the tree, prestige and
 * automation/offline — each topic written truthfully against the live constants. The
 * contract (types + the CODEX_MECHANICS export) stays fixed so the panel, app wiring
 * and test can be authored against it in parallel.
 */

/**
 * One encyclopaedia topic: a stable id, a heading and a list of paragraphs.
 * `body` is an array of plain-text paragraphs (no markup) — the panel renders each
 * as its own block via dom.h (never innerHTML), so the text is treated as data only.
 */
export interface CodexTopic {
  /** Stable, unique id (used for anchors / keys and asserted unique by the test). */
  id: string
  /** Display heading (PL). */
  title: string
  /** Paragraphs of explanatory text (PL); each entry is one paragraph. */
  body: string[]
}

/**
 * One chapter of the mechanics encyclopaedia: a heading grouping related
 * {@link CodexTopic}s (e.g. all of combat). The panel renders a chapter as an h2
 * with its topics as h3 sections beneath it.
 */
export interface CodexChapter {
  /** Stable, unique id (used for anchors / keys and asserted unique by the test). */
  id: string
  /** Display heading (PL). */
  title: string
  /** Topics in display order. */
  topics: CodexTopic[]
}

/**
 * Mechanics chapters — the part of the Codex that cannot be generated from the
 * content tables. PL, true to the code. The full set: economy, combat, raids/defence,
 * siege/scouting, conquest, the tree, prestige and automation/offline. Every chapter
 * and topic id is unique (asserted by the test); each topic carries a non-empty title
 * and at least one paragraph.
 */
export const CODEX_MECHANICS: CodexChapter[] = [
  {
    id: 'ekonomia',
    title: 'Gospodarka',
    topics: [
      {
        id: 'surowce',
        title: 'Surowce, produkcja i magazyn',
        body: [
          'Każda wioska gospodaruje trzema surowcami: drewnem, gliną i żelazem. Wytwarzają je trzy budynki produkcyjne — tartak (drewno), cegielnia (glina) i huta żelaza (żelazo) — a każdy ich poziom dokłada stały przyrost na sekundę. Bazowo tartak daje najwięcej, glina nieco mniej, a żelazo najwolniej, więc to żelazo jest najczęściej wąskim gardłem rozbudowy.',
          'Produkcja nalicza się płynnie w czasie (przyrost razy upływające sekundy) i jest taka sama, czy patrzysz na grę, czy nie. Surowce gromadzą się aż do pojemności magazynu — spichlerz podnosi ją o stałą wartość na poziom. Po osiągnięciu limitu nadwyżka przepada, więc warto rozbudowywać spichlerz, zanim magazyn zacznie się przelewać.',
          'Surowce są lokalne — każda wioska ma własny zapas, produkcję i magazyn. Wyjątkiem jest drzewo rozwoju, które kupuje się ze wspólnej puli wszystkich wiosek (patrz rozdział o rozwoju). Mnożniki produkcji i pojemności z drzewa rozwoju oraz prestiżu nakładają się na bazę z budynków: mnożniki mnożą się między sobą, a redukcje (np. kosztów) dodają i są przycinane do limitu.',
        ],
      },
      {
        id: 'populacja',
        title: 'Populacja i rekrutacja',
        body: [
          'Każda jednostka zajmuje miejsce w populacji wioski, a limit populacji wyznacza zagroda — każdy jej poziom dokłada stałą pulę miejsc. Większość jednostek waży 1, ale jednostki specjalne są cięższe: szlachcic, taran i katapulta zajmują wielokrotnie więcej miejsca, więc ich armia szybko wyczerpuje zagrodę.',
          'Rekrutacja rusza po zbudowaniu koszar (poziom 1). Zamówione jednostki trafiają do kolejki i szkolą się pojedynczo, jedna po drugiej; czas szkolenia jednej jednostki to jej bazowy czas pomnożony przez mnożnik tempa. Każdy poziom koszar skraca czas o 5% (mnożnikowo, z twardym dolnym ograniczeniem), a osobno skraca go gałąź szkolenia w drzewie rozwoju — łącznie nigdy do zera.',
          'Limit populacji liczy zarówno jednostki już wyszkolone, jak i te czekające w kolejce, więc nie da się zamówić więcej, niż zdoła wyżywić zagroda. Rekrutacja kosztuje surowce z lokalnego zapasu wioski; zabraknie miejsca lub surowców — zamówienia po prostu nie przyjmiesz.',
        ],
      },
    ],
  },
  {
    id: 'walka',
    title: 'Walka',
    topics: [
      {
        id: 'moc-armii',
        title: 'Moc ataku i obrony',
        body: [
          'Bitwa rozstrzygana jest na podstawie sumarycznej mocy obu stron, a nie pojedynczych starć jednostka po jednostce. Moc ataku armii to suma (liczba jednostek × atak danego typu) ze wszystkich jednostek w armii.',
          'Moc obrony liczona jest analogicznie z wartości obrony przed piechotą — wszyscy przeciwnicy w grze (barbarzyńcy i najeźdźcy) to piechota, więc to ten profil obrony decyduje o starciu.',
          'Bonusy z drzewa rozwoju i prestiżu działają jako mnożniki nałożone na całą sumę: gałąź militariów zwiększa moc ataku, a fortyfikacji — moc obrony. Mnożnik stosowany jest jednolicie do całej armii, więc nie zmienia samej reguły rozstrzygania, a jedynie finalne liczby.',
        ],
      },
      {
        id: 'rozstrzygniecie',
        title: 'Kto wygrywa i jakie ponosi straty',
        body: [
          'Wygrywa strona o ściśle wyższej mocy. Przy remisie (oraz gdy atakujący nie wnosi żadnej mocy) wygrywa obrońca.',
          'Strona przegrana jest niemal całkowicie rozbijana. Straty zwycięzcy zależą od tego, jak wyrównane było starcie: ułamek strat to (moc słabszego / moc silniejszego) podniesione do potęgi 1,5.',
          'W praktyce miażdżąca przewaga oznacza zwycięstwo prawie bez strat, a ledwie wygrana bitwa potrafi kosztować większość armii. Dlatego opłaca się atakować z wyraźnym zapasem siły — zwłaszcza że mała armia może wygrać, a i tak stopnieć do zera.',
        ],
      },
      {
        id: 'szczescie',
        title: 'Szczęście w walce',
        body: [
          'Każde rozstrzygnięte starcie (atak gracza oraz najazd na gracza) modyfikuje losowo moc strony atakującej o ±25%. To symetryczny zakres o średniej równej 1,0 — na dłuższą metę szczęście się znosi.',
          'Losowanie pochodzi z deterministycznego, zapisywanego ziarna RNG i odbywa się dokładnie raz na każdą rozstrzygniętą bitwę. Dzięki temu wynik jest powtarzalny i identyczny online, offline oraz w symulacji.',
          'Automatyczny atak planuje zawsze pod najgorsze możliwe szczęście (−25%): wysyła armię tylko na cele, które pokona i z których wróci nawet przy najgorszym losowaniu.',
        ],
      },
    ],
  },
  {
    id: 'najazdy-obrona',
    title: 'Najazdy i obrona',
    topics: [
      {
        id: 'najazdy',
        title: 'Najazdy barbarzyńców',
        body: [
          'Każda aktywna wioska jest co jakiś czas najeżdżana przez barbarzyńców. Zegar najazdu odlicza co 15 minut. Świeża osada bez rozbudowy, jednostek i wypraw jest na razie pomijana — najazdy zaczynają się, gdy cokolwiek zbudujesz, wyszkolisz lub wyślesz armię.',
          'Siła najazdu rośnie wraz z rozwojem wioski: bazowa wartość, doliczenie za łączną sumę poziomów budynków oraz część mocy obronnej całej armii wioski. Najazd broni się tylko garnizon stacjonujący w domu — armia wysłana na wyprawę nie liczy się do obrony, więc atakowanie odsłania wioskę.',
          'Odparty najazd nie powoduje żadnych strat ani kradzieży. Najazd, który się przebije, zabiera część obrońców oraz 20% każdego surowca z magazynu. Straty i kradzież nigdy nie zejdą poniżej zera.',
        ],
      },
      {
        id: 'mur',
        title: 'Mur i obrona wioski',
        body: [
          'Mur to budynek czysto obronny. Każdy poziom zwiększa siłę obrony wioski przed najazdami o 5%, do +50% przy maksymalnym (10) poziomie.',
          'Bonus muru mnoży moc obrony garnizonu broniącego wioski. Wioska bez muru ma mnożnik równy 1 (brak zmiany), więc mur jest opcjonalną inwestycją, a nie częścią obowiązkowej kolejności budowy.',
          'Mur kumuluje się z bonusem obrony z drzewa rozwoju (gałąź fortyfikacji): im wyższy mur, tym więcej najazdów odpartych i tym mniejsze straty w tych, które się przebiją. Mur nie wpływa na atak, produkcję ani na przejmowanie wiosek.',
        ],
      },
    ],
  },
  {
    id: 'oblezenie-zwiad',
    title: 'Oblężenie i zwiad',
    topics: [
      {
        id: 'zwiad',
        title: 'Zwiad i mgła wojny',
        body: [
          'Zwiadowca to narzędzie rozpoznania, nie żołnierz. Wysłany na obóz barbarzyński odkrywa jego obronę i łup, po czym wraca bez walki — nie bije się i nie bierze łupu.',
          'Do czasu zwiadu obrona i łup obozu są ukryte (mgła wojny). Zwiad pozwala więc oszacować, czy armia poradzi sobie z celem, zanim ją wyślesz.',
          'Zwiadowca jest najszybszą jednostką, aby rozpoznanie wyprzedzało armię. Automatyczny atak nie wysyła zwiadowców (nie wnoszą mocy ataku).',
        ],
      },
      {
        id: 'taran',
        title: 'Taran — osłabienie obrony',
        body: [
          'Taran to machina oblężnicza dołączana do armii atakującej. Każdy taran obniża skuteczną obronę atakowanego obozu o 2% w tej konkretnej bitwie, co pozwala rozbić cel, którego ta sama armia nie pokonałaby bez wsparcia.',
          'Redukcja ma twardy limit: tarany nie zdejmą więcej niż 60% obrony celu (czynnik nie spadnie poniżej 0,4), bez względu na ich liczbę.',
          'Taran sam słabo walczy i nie bierze łupu, jest ciężki i wolny, a do jego szkolenia wymagany jest Pałac. Automatyczny atak nigdy nie wysyła taranów — oblężenie to decyzja ręczna.',
        ],
      },
      {
        id: 'katapulta',
        title: 'Katapulta — burzenie poziomu',
        body: [
          'Katapulta to machina oblężnicza, która po wygranym ataku trwale obniża poziom obozu, zmniejszając jego przyszłą obronę i łup (taktyka spalonej ziemi).',
          'Co 5 katapult burzy jeden poziom obozu, ale jeden atak zburzy najwyżej 3 poziomy. Poziom obozu nigdy nie spada poniżej 1 — katapulta osłabia cel, lecz go nie likwiduje.',
          'Tak jak taran, katapulta ledwie walczy, nie dźwiga łupu, jest wolna i wymaga Pałacu. Automatyczny atak nigdy nie wysyła katapult.',
        ],
      },
    ],
  },
  {
    id: 'przejecia',
    title: 'Przejęcia i ekspansja',
    topics: [
      {
        id: 'lojalnosc',
        title: 'Lojalność i przejmowanie wiosek',
        body: [
          'Wioski barbarzyńskie przejmuje się nie jednym ciosem, lecz wykruszaniem lojalności. Wymaga to szlachcica — drogiej, ciężkiej i wolnej jednostki odblokowywanej przez Pałac. Szlachcica dołącza się do armii atakującej: każdy szlachcic, który PRZEŻYJE wygraną bitwę, obniża lojalność celu o 25 punktów.',
          'Lojalność startuje ze 100 i powoli się regeneruje między atakami, więc przeciągające się oblężenie traci grunt. W praktyce pojedynczy szlachcic potrzebuje około czterech czystych zwycięstw, by zbić lojalność do zera — regeneracja podnosi tę liczbę nieco wyżej. Gdy lojalność spadnie do zera, obóz natychmiast staje się twoją wioską w tym samym miejscu na mapie.',
          'Szlachcic jest bardzo kosztowny w surowcach i populacji, a w dodatku sam słabo walczy, więc trzeba go osłaniać armią ofensywną zdolną wygrać bitwę. Automatyczny atak nigdy nie wysyła szlachciców — przejmowanie wiosek to zawsze decyzja ręczna.',
        ],
      },
      {
        id: 'zakladanie',
        title: 'Zakładanie nowych wiosek',
        body: [
          'Poza przejmowaniem obozów imperium można rozrastać, zakładając zupełnie nowe, puste wioski na mapie. Koszt rośnie geometrycznie z liczbą posiadanych wiosek, więc każda kolejna osada to coraz poważniejsza inwestycja. Płaci się surowcami z jednej wybranej wioski.',
          'Geometria mapy pilnuje, by imperium rosło stopniowo na zewnątrz: nowe pole musi zachować minimalny odstęp od każdej innej wioski (twojej i barbarzyńskiej) i jednocześnie leżeć w zasięgu którejś z twoich wiosek. Nie da się więc osiedlić na drugim końcu mapy ani wcisnąć osady tuż obok istniejącej.',
          'Świeżo założona wioska startuje z podstawowymi budynkami i własną, niezależną gospodarką — od zera buduje produkcję, magazyn, populację i armię. Dziedziczy za to globalne mnożniki z drzewa rozwoju i prestiżu, które obowiązują w całym imperium.',
        ],
      },
    ],
  },
  {
    id: 'rozwoj',
    title: 'Rozwój i prestiż',
    topics: [
      {
        id: 'drzewo',
        title: 'Drzewo rozwoju i wspólna pula',
        body: [
          'Drzewo rozwoju to globalna konstelacja perków obowiązujących całe imperium, nie pojedynczą wioskę. Węzły kupuje się ze WSPÓLNEJ puli surowców — sumy drewna, gliny i żelaza ze wszystkich wiosek. Zakup ściąga koszt po kolei z kolejnych wiosek, nigdy nie schodząc poniżej zera, więc bogata stolica może opłacić rozwój za całe państwo.',
          'Węzły układają się w gałęzie tematyczne (m.in. ekonomia, magazyn, osadnictwo, militaria, fortyfikacja, logistyka, grabież, budownictwo, szkolenie). Każdy węzeł ma wymagania wstępne — odblokowujesz go, dopiero gdy masz wcześniejsze węzły na ścieżce — oraz skończony maksymalny poziom: od jednorazowych przełączników po drobne bonusy rozłożone na wiele poziomów.',
          'Efekty kumulują się kontem-szeroko: mnożniki produkcji, magazynu, populacji, ataku, obrony i łupu mnożą się, a redukcje kosztów, czasu szkolenia i czasu marszu sumują się i są przycinane do bezpiecznych limitów (rozbudowa nigdy nie jest darmowa, marsz nigdy natychmiastowy). Część gałęzi odblokowuje też rutyny automatyzacji. Drzewo rozrasta się wszerz — nowe gałęzie i liście — a nie w nieskończoną głąb.',
        ],
      },
      {
        id: 'prestiz',
        title: 'Prestiż i ascensja',
        body: [
          'Ascensja to dobrowolny reset bieżącego biegu w zamian za trwały postęp. Po ascensji bieg zaczyna się od nowa: jedna świeża stolica w centrum mapy, na nowo wygenerowany świat barbarzyńców, wyczyszczone drzewo rozwoju i dziennik walk. Konto prestiżu — punkty, sumy i poziomy węzłów prestiżu — przetrwa reset.',
          'Za ascensję dostajesz punkty prestiżu (PP). Ich liczba zależy od postępu biegu (łączne poziomy budynków, kupione poziomy drzewa rozwoju oraz liczba wiosek) przez pierwiastek — dlatego każda kolejna ascensja daje proporcjonalnie mniej PP za tę samą surową ilość postępu. To klasyczna krzywa prestiżu: reset wciąż się opłaca, ale nie nakręca się w nieskończoność.',
          'PP wydaje się na trwałe drzewo prestiżu (kategorie: potęga, dobrobyt, panowanie). Jego węzły działają tak jak drzewo rozwoju — mają wymagania i skończone poziomy — ale ich bonusy są permanentne i obowiązują w każdym kolejnym biegu. Część węzłów daje startowy zastrzyk surowców dla nowej stolicy, dzięki czemu każdy restart jest szybszy od poprzedniego.',
        ],
      },
    ],
  },
  {
    id: 'automatyzacja-czas',
    title: 'Automatyzacja i czas',
    topics: [
      {
        id: 'automatyzacja',
        title: 'Automatyzacja',
        body: [
          'Gra potrafi prowadzić część rutyn za ciebie. Są trzy: auto-budowa stawia najtańszy budynek, na który aktualnie stać wioskę; auto-rekrutacja utrzymuje wybraną jednostkę na zadanym stanie liczebnym; auto-atak wysyła bezczynną armię na najbliższy obóz, który na pewno pokona.',
          'Każdą rutynę trzeba najpierw ODBLOKOWAĆ w drzewie rozwoju (osobne węzły-przełączniki), a potem WŁĄCZYĆ jej przełącznik. Dopóki rutyna jest zablokowana albo wyłączona, gra zachowuje się dokładnie jak bez automatyzacji.',
          'Auto-atak gra zachowawczo: planuje pod najgorsze możliwe szczęście (−25%) i wysyła armię tylko tam, gdzie zwycięstwo jest pewne i przynajmniej jedna jednostka wróci do domu. Nigdy nie wysyła szlachciców (przejęcia są ręczne), zwiadowców (nie wnoszą mocy) ani machin oblężniczych (taran i katapulta to decyzje celowane). Rutyny są samoograniczające: wykonują co najwyżej jedną akcję na krok i zatrzymują się, gdy brak surowców, miejsca lub celu — więc nie powodują zamrożenia gry.',
        ],
      },
      {
        id: 'offline',
        title: 'Postęp offline',
        body: [
          'Gra liczy czas twojej nieobecności. Po powrocie nalicza postęp za miniony okres: produkcję, ukończone rekrutacje, marsze i ich rozstrzygnięcia, najazdy oraz — jeśli włączona — automatyzację.',
          'Czas offline jest ograniczony do 8 godzin: dłuższa przerwa liczona jest tak, jakby trwała równo 8 godzin. Nadrabianie biegnie tymi samymi, stałymi krokami czasu co gra na żywo, więc stan po powrocie jest identyczny z tym, jak gdybyś grał bez przerwy — łącznie z losowaniami szczęścia w walce, które pochodzą z zapisywanego, deterministycznego ziarna.',
          'W praktyce oznacza to, że bezpiecznie zostawić grę: wrócisz do zgromadzonych surowców i wyników bitew. Pamiętaj jednak, że najazdy też naliczają się offline, a armia wysłana na wyprawę nie broni wioski — więc agresywne zostawienie wojska poza domem odsłania osadę także podczas twojej nieobecności.',
        ],
      },
    ],
  },
]
