import type { ResourceId } from '../engine/state'

/**
 * Tech (passive) tree catalogue — PURE DATA (no engine logic lives here).
 *
 * The global, account-wide passive tree (M3.1) is a Path-of-Exile-style radial
 * constellation of CLUSTERS (the authoring unit: one notable + a ring of minor
 * nodes, with a handful of gateways on the junctions). A node has a FINITE
 * `maxLevel` (1..10, chosen by archetype), costs resources from the GLOBAL pool
 * (summed across all villages) and applies an ECONOMIC multiplier (production /
 * storage / population). Effects are folded in one place —
 * `recomputeVillageDerived` via `aggregateTechMods` — so the rest of the
 * simulation (combat, marches) is untouched until M3.2.
 *
 * Import discipline: this module imports only the *type* `ResourceId` from
 * state.ts (erased at runtime), so it has no runtime dependency back on the engine
 * and can never form an initialisation cycle (mirrors content/buildings.ts).
 *
 * SHAPE (the contract): the types below, plus the full tree — 180 nodes across 30
 * clusters in 9 categories. The 3 economic arms (economy/storage/settlement, 72
 * nodes / 12 clusters) are the M3.1 base; M3.2 adds 6 combat/logistics/cost arms
 * (military/fortification/logistics/plunder/construction/training, 108 nodes / 18
 * clusters). Every cluster is a notable (maxLevel 2-3) + a ring of minors (maxLevel
 * 7-10); 9 expensive gateways (maxLevel 1) sit on the junctions into the "master"
 * clusters. Prerequisites form a DAG with no cycles where every node is reachable
 * from a root and every node has a real effect (perLevel > 0). No x/y here — the
 * radial layout is COMPUTED from the prerequisite topology by systems/techLayout.ts
 * (never hand-placed). Costs (baseCost/costFactor) are provisional — the Balance
 * phase tunes them so the tree is a real sink that scales with the empire and is
 * bought gradually.
 */

/**
 * Top-level branch of the constellation. The three M3.1 economic categories map 1:1
 * onto the three economic effects (economy -> production, storage -> storage,
 * settlement -> population). M3.2 adds six combat/logistics/cost arms, each mapped to
 * one of the new effect kinds (military -> attack, fortification -> defense,
 * logistics -> march speed, plunder -> loot, construction -> cost reduction,
 * training -> recruit speed). The radial layout (systems/techLayout.ts) treats every
 * category as an arm automatically, so adding a category is a pure data change.
 */
export type TechCategory =
  | 'economy'
  | 'storage'
  | 'settlement'
  | 'military'
  | 'fortification'
  | 'logistics'
  | 'plunder'
  | 'construction'
  | 'training'

/**
 * Node role, which fixes the `maxLevel` band (CLAUDE.md tree rule):
 *  - minor:    drobny bonus na poziom -> maxLevel 7-10
 *  - notable:  silny nazwany efekt    -> maxLevel 2-3
 *  - gateway:  binarne odblokowanie / rozjazd -> maxLevel 1 (drogie)
 */
export type TechArchetype = 'minor' | 'notable' | 'gateway'

/**
 * What a tech node *does*, as a discriminated union. `perLevel` is a FRACTION added
 * per owned level to the relevant modifier (e.g. 0.03 = +3%/level); aggregateTechMods
 * (systems/tech.ts) sums `perLevel * level` across nodes per kind.
 *
 * The three ECONOMY kinds fold into a `1 + Σ` multiplier:
 *  - production_mult: scales production. `resource` absent = ALL resources.
 *  - storage_mult:    scales the storage cap.
 *  - pop_mult:        scales the population cap.
 *
 * M3.2 adds six kinds. Three fold into a FRACTION (Σ, clamped — a reduction of the
 * underlying time/cost):
 *  - cost_reduction: fraction off building cost (clamped 0..0.8).
 *  - recruit_speed:  fraction off recruitment time (clamped 0..0.75).
 *  - march_speed:    fraction off march time (clamped 0..0.75).
 * Three fold into a `1 + Σ` multiplier (>= 1):
 *  - attack_mult:    scales army attack power.
 *  - defense_mult:   scales army defence power.
 *  - loot_mult:      scales loot hauled from a target.
 *
 * Each new kind is consumed by exactly one system (buildings / recruitment / marches /
 * combat), threaded there via {@link TechModifiers}; the economy kinds keep folding
 * through recomputeVillageDerived as before.
 */
export type TechEffect =
  | { kind: 'production_mult'; resource?: ResourceId; perLevel: number }
  | { kind: 'storage_mult'; perLevel: number }
  | { kind: 'pop_mult'; perLevel: number }
  | { kind: 'cost_reduction'; perLevel: number }
  | { kind: 'recruit_speed'; perLevel: number }
  | { kind: 'march_speed'; perLevel: number }
  | { kind: 'attack_mult'; perLevel: number }
  | { kind: 'defense_mult'; perLevel: number }
  | { kind: 'loot_mult'; perLevel: number }

export interface TechNode {
  /** Stable id (the key under {@link TECH_NODES}); what prerequisites point at. */
  id: string
  /** Display name (PL). */
  name: string
  /** Short description (PL). */
  desc: string
  category: TechCategory
  /** Id of the owning cluster (authoring unit: notable + ring of minors). */
  cluster: string
  archetype: TechArchetype
  /** Finite upgrade ceiling, 1..10, sized to the archetype (CLAUDE.md). */
  maxLevel: number
  /** Ids of nodes that must be at level >= 1 before this node is available (DAG). */
  prerequisites: string[]
  /** Cost of the *first* level (level 0 -> 1), per resource. */
  baseCost: { wood: number; clay: number; iron: number }
  /** Geometric cost growth per owned level. */
  costFactor: number
  effect: TechEffect
}

/**
 * The full STARTING passive tree (M3.1). 72 nodes, 12 clusters, 3 categories:
 *
 *  - economy   (6 clusters): production_mult — eco_core (entry, all res) -> three
 *              per-resource clusters (wood/clay/iron) -> eco_industry (all res,
 *              converges the three) -> eco_master (all res, behind the eco gateway).
 *  - storage   (3 clusters): storage_mult — sto_core -> sto_deep -> sto_master
 *              (behind the storage gateway).
 *  - settlement(3 clusters): pop_mult — set_core -> set_deep -> set_master (behind
 *              the settlement gateway).
 *
 * Each cluster = one notable (maxLevel 2-3, strong named effect) + a ring of 4-5
 * minors (maxLevel 7-10, drobny effect). Three gateways (maxLevel 1, drogie) gate
 * the "master" clusters. Roots (eco_root/sto_root/set_root) have no prerequisites
 * — one per category. Prerequisites are a DAG with no cycles; every node is
 * reachable from a root and every node has a real effect (perLevel > 0).
 *
 * Object key order IS the stable source order driving every order-sensitive pass
 * (aggregateTechMods, layout, validation, the sim) — keep new nodes appended when
 * extending in M3.2 so saves/round-trips stay reproducible.
 */
export const TECH_NODES: Record<string, TechNode> = {
  // =====================================================================
  // ECONOMY arm — production_mult
  // =====================================================================

  // --- eco_core: entry cluster (all resources) -------------------------
  eco_root: {
    id: 'eco_root',
    name: 'Gospodarka',
    desc: 'Wejście do gałęzi gospodarczej. Niewielki wzrost produkcji wszystkich surowców na poziom.',
    category: 'economy',
    cluster: 'eco_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 120, clay: 120, iron: 120 },
    costFactor: 1.28,
    effect: { kind: 'production_mult', perLevel: 0.02 },
  },
  eco_core_n: {
    id: 'eco_core_n',
    name: 'Sprawne warsztaty',
    desc: 'Notable gospodarki: znaczny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_core',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['eco_root'],
    baseCost: { wood: 400, clay: 400, iron: 400 },
    costFactor: 1.55,
    effect: { kind: 'production_mult', perLevel: 0.06 },
  },
  eco_core_m1: {
    id: 'eco_core_m1',
    name: 'Drobni rzemieślnicy',
    desc: 'Marginalny, lecz głęboki wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_core',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['eco_root'],
    baseCost: { wood: 150, clay: 150, iron: 150 },
    costFactor: 1.28,
    effect: { kind: 'production_mult', perLevel: 0.012 },
  },
  eco_core_m2: {
    id: 'eco_core_m2',
    name: 'Targowe szlaki',
    desc: 'Drobny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_root'],
    baseCost: { wood: 160, clay: 160, iron: 160 },
    costFactor: 1.28,
    effect: { kind: 'production_mult', perLevel: 0.02 },
  },
  eco_core_m3: {
    id: 'eco_core_m3',
    name: 'Cechy rzemieślnicze',
    desc: 'Drobny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_core_n'],
    baseCost: { wood: 170, clay: 170, iron: 170 },
    costFactor: 1.28,
    effect: { kind: 'production_mult', perLevel: 0.02 },
  },
  eco_core_m4: {
    id: 'eco_core_m4',
    name: 'Wydajne narzędzia',
    desc: 'Wyraźny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['eco_core_n'],
    baseCost: { wood: 200, clay: 200, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', perLevel: 0.025 },
  },

  // --- eco_wood: drewno cluster ----------------------------------------
  eco_wood_n: {
    id: 'eco_wood_n',
    name: 'Leśne gospodarstwa',
    desc: 'Notable drewna: znaczny wzrost produkcji drewna.',
    category: 'economy',
    cluster: 'eco_wood',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['eco_core_n'],
    baseCost: { wood: 800, clay: 500, iron: 500 },
    costFactor: 1.5,
    effect: { kind: 'production_mult', resource: 'wood', perLevel: 0.08 },
  },
  eco_wood_m1: {
    id: 'eco_wood_m1',
    name: 'Ostrzone topory',
    desc: 'Wzrost produkcji drewna.',
    category: 'economy',
    cluster: 'eco_wood',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_wood_n'],
    baseCost: { wood: 280, clay: 180, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'wood', perLevel: 0.025 },
  },
  eco_wood_m2: {
    id: 'eco_wood_m2',
    name: 'Spławianie drewna',
    desc: 'Wzrost produkcji drewna.',
    category: 'economy',
    cluster: 'eco_wood',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_wood_n'],
    baseCost: { wood: 300, clay: 200, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'wood', perLevel: 0.025 },
  },
  eco_wood_m3: {
    id: 'eco_wood_m3',
    name: 'Karczownicy',
    desc: 'Wyraźny wzrost produkcji drewna.',
    category: 'economy',
    cluster: 'eco_wood',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['eco_wood_m1'],
    baseCost: { wood: 320, clay: 200, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'wood', perLevel: 0.03 },
  },
  eco_wood_m4: {
    id: 'eco_wood_m4',
    name: 'Sezonowanie drewna',
    desc: 'Marginalny, głęboki wzrost produkcji drewna.',
    category: 'economy',
    cluster: 'eco_wood',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['eco_wood_m2'],
    baseCost: { wood: 260, clay: 160, iron: 160 },
    costFactor: 1.28,
    effect: { kind: 'production_mult', resource: 'wood', perLevel: 0.015 },
  },
  eco_wood_m5: {
    id: 'eco_wood_m5',
    name: 'Trakty leśne',
    desc: 'Wzrost produkcji drewna.',
    category: 'economy',
    cluster: 'eco_wood',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_wood_n'],
    baseCost: { wood: 300, clay: 200, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'wood', perLevel: 0.02 },
  },

  // --- eco_clay: glina cluster -----------------------------------------
  eco_clay_n: {
    id: 'eco_clay_n',
    name: 'Wielkie gliniska',
    desc: 'Notable gliny: znaczny wzrost produkcji gliny.',
    category: 'economy',
    cluster: 'eco_clay',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['eco_core_n'],
    baseCost: { wood: 500, clay: 800, iron: 500 },
    costFactor: 1.5,
    effect: { kind: 'production_mult', resource: 'clay', perLevel: 0.08 },
  },
  eco_clay_m1: {
    id: 'eco_clay_m1',
    name: 'Ubijaki gliny',
    desc: 'Wzrost produkcji gliny.',
    category: 'economy',
    cluster: 'eco_clay',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_clay_n'],
    baseCost: { wood: 180, clay: 280, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'clay', perLevel: 0.025 },
  },
  eco_clay_m2: {
    id: 'eco_clay_m2',
    name: 'Suszarnie cegieł',
    desc: 'Wzrost produkcji gliny.',
    category: 'economy',
    cluster: 'eco_clay',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_clay_n'],
    baseCost: { wood: 200, clay: 300, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'clay', perLevel: 0.025 },
  },
  eco_clay_m3: {
    id: 'eco_clay_m3',
    name: 'Głębokie wykopy',
    desc: 'Wyraźny wzrost produkcji gliny.',
    category: 'economy',
    cluster: 'eco_clay',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['eco_clay_m1'],
    baseCost: { wood: 200, clay: 320, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'clay', perLevel: 0.03 },
  },
  eco_clay_m4: {
    id: 'eco_clay_m4',
    name: 'Formy ceglane',
    desc: 'Marginalny, głęboki wzrost produkcji gliny.',
    category: 'economy',
    cluster: 'eco_clay',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['eco_clay_m2'],
    baseCost: { wood: 160, clay: 260, iron: 160 },
    costFactor: 1.28,
    effect: { kind: 'production_mult', resource: 'clay', perLevel: 0.015 },
  },
  eco_clay_m5: {
    id: 'eco_clay_m5',
    name: 'Piece do wypału',
    desc: 'Wzrost produkcji gliny.',
    category: 'economy',
    cluster: 'eco_clay',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_clay_n'],
    baseCost: { wood: 200, clay: 300, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'clay', perLevel: 0.02 },
  },

  // --- eco_iron: żelazo cluster ----------------------------------------
  eco_iron_n: {
    id: 'eco_iron_n',
    name: 'Bogate złoża',
    desc: 'Notable żelaza: znaczny wzrost produkcji żelaza.',
    category: 'economy',
    cluster: 'eco_iron',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['eco_core_n'],
    baseCost: { wood: 500, clay: 500, iron: 800 },
    costFactor: 1.5,
    effect: { kind: 'production_mult', resource: 'iron', perLevel: 0.08 },
  },
  eco_iron_m1: {
    id: 'eco_iron_m1',
    name: 'Miechy kowalskie',
    desc: 'Wzrost produkcji żelaza.',
    category: 'economy',
    cluster: 'eco_iron',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_iron_n'],
    baseCost: { wood: 180, clay: 180, iron: 280 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'iron', perLevel: 0.025 },
  },
  eco_iron_m2: {
    id: 'eco_iron_m2',
    name: 'Sztolnie',
    desc: 'Wzrost produkcji żelaza.',
    category: 'economy',
    cluster: 'eco_iron',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_iron_n'],
    baseCost: { wood: 200, clay: 200, iron: 300 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'iron', perLevel: 0.025 },
  },
  eco_iron_m3: {
    id: 'eco_iron_m3',
    name: 'Wytapianie rud',
    desc: 'Wyraźny wzrost produkcji żelaza.',
    category: 'economy',
    cluster: 'eco_iron',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['eco_iron_m1'],
    baseCost: { wood: 200, clay: 200, iron: 320 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'iron', perLevel: 0.03 },
  },
  eco_iron_m4: {
    id: 'eco_iron_m4',
    name: 'Hartowanie',
    desc: 'Marginalny, głęboki wzrost produkcji żelaza.',
    category: 'economy',
    cluster: 'eco_iron',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['eco_iron_m2'],
    baseCost: { wood: 160, clay: 160, iron: 260 },
    costFactor: 1.28,
    effect: { kind: 'production_mult', resource: 'iron', perLevel: 0.015 },
  },
  eco_iron_m5: {
    id: 'eco_iron_m5',
    name: 'Dymarki',
    desc: 'Wzrost produkcji żelaza.',
    category: 'economy',
    cluster: 'eco_iron',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_iron_n'],
    baseCost: { wood: 200, clay: 200, iron: 300 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', resource: 'iron', perLevel: 0.02 },
  },

  // --- eco_industry: konwergencja (all res) ----------------------------
  eco_industry_n: {
    id: 'eco_industry_n',
    name: 'Manufaktury',
    desc: 'Notable przemysłu: silny wzrost produkcji wszystkich surowców. Zbiega trzy gałęzie surowcowe.',
    category: 'economy',
    cluster: 'eco_industry',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['eco_wood_n', 'eco_clay_n', 'eco_iron_n'],
    baseCost: { wood: 2000, clay: 2000, iron: 2000 },
    costFactor: 1.55,
    effect: { kind: 'production_mult', perLevel: 0.07 },
  },
  eco_industry_m1: {
    id: 'eco_industry_m1',
    name: 'Podział pracy',
    desc: 'Wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_industry',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_industry_n'],
    baseCost: { wood: 700, clay: 700, iron: 700 },
    costFactor: 1.32,
    effect: { kind: 'production_mult', perLevel: 0.02 },
  },
  eco_industry_m2: {
    id: 'eco_industry_m2',
    name: 'Koła wodne',
    desc: 'Wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_industry',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_industry_n'],
    baseCost: { wood: 750, clay: 750, iron: 750 },
    costFactor: 1.32,
    effect: { kind: 'production_mult', perLevel: 0.02 },
  },
  eco_industry_m3: {
    id: 'eco_industry_m3',
    name: 'Magazyny surowca',
    desc: 'Wyraźny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_industry',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['eco_industry_m1'],
    baseCost: { wood: 800, clay: 800, iron: 800 },
    costFactor: 1.33,
    effect: { kind: 'production_mult', perLevel: 0.025 },
  },
  eco_industry_m4: {
    id: 'eco_industry_m4',
    name: 'Księgi rachunkowe',
    desc: 'Marginalny, głęboki wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_industry',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['eco_industry_m2'],
    baseCost: { wood: 650, clay: 650, iron: 650 },
    costFactor: 1.3,
    effect: { kind: 'production_mult', perLevel: 0.012 },
  },
  eco_industry_m5: {
    id: 'eco_industry_m5',
    name: 'Gildie kupieckie',
    desc: 'Wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_industry',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_industry_n'],
    baseCost: { wood: 750, clay: 750, iron: 750 },
    costFactor: 1.32,
    effect: { kind: 'production_mult', perLevel: 0.02 },
  },

  // --- eco_master: gateway + szczyt gospodarki (all res) ---------------
  eco_gateway: {
    id: 'eco_gateway',
    name: 'Rewolucja przemysłowa',
    desc: 'Brama przemysłu (drogie, jednorazowe): trwały wzrost produkcji wszystkich surowców. Odsłania szczytowy klaster gospodarki.',
    category: 'economy',
    cluster: 'eco_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['eco_industry_n'],
    baseCost: { wood: 8000, clay: 8000, iron: 8000 },
    costFactor: 1.0,
    effect: { kind: 'production_mult', perLevel: 0.05 },
  },
  eco_master_n: {
    id: 'eco_master_n',
    name: 'Imperium handlowe',
    desc: 'Szczytowy notable gospodarki: bardzo silny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_master',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['eco_gateway'],
    baseCost: { wood: 6000, clay: 6000, iron: 6000 },
    costFactor: 1.6,
    effect: { kind: 'production_mult', perLevel: 0.1 },
  },
  eco_master_m1: {
    id: 'eco_master_m1',
    name: 'Banki kupieckie',
    desc: 'Znaczny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_master',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_master_n'],
    baseCost: { wood: 2500, clay: 2500, iron: 2500 },
    costFactor: 1.35,
    effect: { kind: 'production_mult', perLevel: 0.025 },
  },
  eco_master_m2: {
    id: 'eco_master_m2',
    name: 'Floty handlowe',
    desc: 'Znaczny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_master',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['eco_master_n'],
    baseCost: { wood: 2700, clay: 2700, iron: 2700 },
    costFactor: 1.35,
    effect: { kind: 'production_mult', perLevel: 0.025 },
  },
  eco_master_m3: {
    id: 'eco_master_m3',
    name: 'Monopole surowcowe',
    desc: 'Silny wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['eco_master_m1'],
    baseCost: { wood: 3000, clay: 3000, iron: 3000 },
    costFactor: 1.36,
    effect: { kind: 'production_mult', perLevel: 0.03 },
  },
  eco_master_m4: {
    id: 'eco_master_m4',
    name: 'Kontrakty dalekosiężne',
    desc: 'Marginalny, głęboki wzrost produkcji wszystkich surowców.',
    category: 'economy',
    cluster: 'eco_master',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['eco_master_m2'],
    baseCost: { wood: 2300, clay: 2300, iron: 2300 },
    costFactor: 1.33,
    effect: { kind: 'production_mult', perLevel: 0.015 },
  },

  // =====================================================================
  // STORAGE arm — storage_mult
  // =====================================================================

  // --- sto_core: entry cluster -----------------------------------------
  sto_root: {
    id: 'sto_root',
    name: 'Magazyny',
    desc: 'Wejście do gałęzi magazynowej. Niewielki wzrost pojemności magazynu na poziom.',
    category: 'storage',
    cluster: 'sto_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 120, clay: 120, iron: 90 },
    costFactor: 1.28,
    effect: { kind: 'storage_mult', perLevel: 0.02 },
  },
  sto_core_n: {
    id: 'sto_core_n',
    name: 'Głębokie składy',
    desc: 'Notable magazynów: znaczny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_core',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['sto_root'],
    baseCost: { wood: 450, clay: 450, iron: 350 },
    costFactor: 1.55,
    effect: { kind: 'storage_mult', perLevel: 0.07 },
  },
  sto_core_m1: {
    id: 'sto_core_m1',
    name: 'Półki i regały',
    desc: 'Marginalny, głęboki wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_core',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['sto_root'],
    baseCost: { wood: 150, clay: 150, iron: 120 },
    costFactor: 1.28,
    effect: { kind: 'storage_mult', perLevel: 0.012 },
  },
  sto_core_m2: {
    id: 'sto_core_m2',
    name: 'Zadaszone składy',
    desc: 'Drobny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['sto_root'],
    baseCost: { wood: 160, clay: 160, iron: 130 },
    costFactor: 1.28,
    effect: { kind: 'storage_mult', perLevel: 0.02 },
  },
  sto_core_m3: {
    id: 'sto_core_m3',
    name: 'Beczki i skrzynie',
    desc: 'Drobny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['sto_core_n'],
    baseCost: { wood: 170, clay: 170, iron: 140 },
    costFactor: 1.28,
    effect: { kind: 'storage_mult', perLevel: 0.02 },
  },
  sto_core_m4: {
    id: 'sto_core_m4',
    name: 'Suche piwnice',
    desc: 'Wyraźny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['sto_core_n'],
    baseCost: { wood: 200, clay: 200, iron: 160 },
    costFactor: 1.3,
    effect: { kind: 'storage_mult', perLevel: 0.025 },
  },

  // --- sto_deep: rozbudowane magazyny ----------------------------------
  sto_deep_n: {
    id: 'sto_deep_n',
    name: 'Wzmocnione spichlerze',
    desc: 'Notable magazynów: duży wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_deep',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['sto_core_n'],
    baseCost: { wood: 1400, clay: 1400, iron: 1100 },
    costFactor: 1.55,
    effect: { kind: 'storage_mult', perLevel: 0.08 },
  },
  sto_deep_m1: {
    id: 'sto_deep_m1',
    name: 'Kamienne fundamenty',
    desc: 'Wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['sto_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 400 },
    costFactor: 1.32,
    effect: { kind: 'storage_mult', perLevel: 0.02 },
  },
  sto_deep_m2: {
    id: 'sto_deep_m2',
    name: 'Wzmocnione belki',
    desc: 'Wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['sto_deep_n'],
    baseCost: { wood: 550, clay: 550, iron: 440 },
    costFactor: 1.32,
    effect: { kind: 'storage_mult', perLevel: 0.02 },
  },
  sto_deep_m3: {
    id: 'sto_deep_m3',
    name: 'Strażnicy zapasów',
    desc: 'Wyraźny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['sto_deep_m1'],
    baseCost: { wood: 600, clay: 600, iron: 480 },
    costFactor: 1.33,
    effect: { kind: 'storage_mult', perLevel: 0.025 },
  },
  sto_deep_m4: {
    id: 'sto_deep_m4',
    name: 'Inwentaryzacja',
    desc: 'Marginalny, głęboki wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_deep',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['sto_deep_m2'],
    baseCost: { wood: 460, clay: 460, iron: 360 },
    costFactor: 1.3,
    effect: { kind: 'storage_mult', perLevel: 0.012 },
  },
  sto_deep_m5: {
    id: 'sto_deep_m5',
    name: 'Zabezpieczenia',
    desc: 'Wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['sto_deep_n'],
    baseCost: { wood: 550, clay: 550, iron: 440 },
    costFactor: 1.32,
    effect: { kind: 'storage_mult', perLevel: 0.02 },
  },

  // --- sto_master: gateway + szczyt magazynów --------------------------
  sto_gateway: {
    id: 'sto_gateway',
    name: 'Wielkie składnice',
    desc: 'Brama magazynów (drogie, jednorazowe): trwały wzrost pojemności magazynu. Odsłania szczytowy klaster magazynowy.',
    category: 'storage',
    cluster: 'sto_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['sto_deep_n'],
    baseCost: { wood: 7000, clay: 7000, iron: 6000 },
    costFactor: 1.0,
    effect: { kind: 'storage_mult', perLevel: 0.05 },
  },
  sto_master_n: {
    id: 'sto_master_n',
    name: 'Cytadele zaopatrzenia',
    desc: 'Szczytowy notable magazynów: bardzo duży wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_master',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['sto_gateway'],
    baseCost: { wood: 5000, clay: 5000, iron: 4000 },
    costFactor: 1.6,
    effect: { kind: 'storage_mult', perLevel: 0.1 },
  },
  sto_master_m1: {
    id: 'sto_master_m1',
    name: 'Podziemne magazyny',
    desc: 'Znaczny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_master',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['sto_master_n'],
    baseCost: { wood: 2200, clay: 2200, iron: 1800 },
    costFactor: 1.35,
    effect: { kind: 'storage_mult', perLevel: 0.025 },
  },
  sto_master_m2: {
    id: 'sto_master_m2',
    name: 'Forteczne spichlerze',
    desc: 'Znaczny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_master',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['sto_master_n'],
    baseCost: { wood: 2400, clay: 2400, iron: 1900 },
    costFactor: 1.35,
    effect: { kind: 'storage_mult', perLevel: 0.025 },
  },
  sto_master_m3: {
    id: 'sto_master_m3',
    name: 'Sieci zaopatrzenia',
    desc: 'Silny wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['sto_master_m1'],
    baseCost: { wood: 2600, clay: 2600, iron: 2100 },
    costFactor: 1.36,
    effect: { kind: 'storage_mult', perLevel: 0.03 },
  },
  sto_master_m4: {
    id: 'sto_master_m4',
    name: 'Rezerwy strategiczne',
    desc: 'Marginalny, głęboki wzrost pojemności magazynu.',
    category: 'storage',
    cluster: 'sto_master',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['sto_master_m2'],
    baseCost: { wood: 2000, clay: 2000, iron: 1600 },
    costFactor: 1.33,
    effect: { kind: 'storage_mult', perLevel: 0.015 },
  },

  // =====================================================================
  // SETTLEMENT arm — pop_mult
  // =====================================================================

  // --- set_core: entry cluster -----------------------------------------
  set_root: {
    id: 'set_root',
    name: 'Osadnictwo',
    desc: 'Wejście do gałęzi osadniczej. Niewielki wzrost limitu populacji na poziom.',
    category: 'settlement',
    cluster: 'set_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 90, clay: 110, iron: 110 },
    costFactor: 1.28,
    effect: { kind: 'pop_mult', perLevel: 0.02 },
  },
  set_core_n: {
    id: 'set_core_n',
    name: 'Żyzne ziemie',
    desc: 'Notable osadnictwa: znaczny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_core',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['set_root'],
    baseCost: { wood: 350, clay: 450, iron: 450 },
    costFactor: 1.55,
    effect: { kind: 'pop_mult', perLevel: 0.07 },
  },
  set_core_m1: {
    id: 'set_core_m1',
    name: 'Nowe zagrody',
    desc: 'Marginalny, głęboki wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_core',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['set_root'],
    baseCost: { wood: 120, clay: 150, iron: 150 },
    costFactor: 1.28,
    effect: { kind: 'pop_mult', perLevel: 0.012 },
  },
  set_core_m2: {
    id: 'set_core_m2',
    name: 'Studnie i ujęcia',
    desc: 'Drobny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['set_root'],
    baseCost: { wood: 130, clay: 160, iron: 160 },
    costFactor: 1.28,
    effect: { kind: 'pop_mult', perLevel: 0.02 },
  },
  set_core_m3: {
    id: 'set_core_m3',
    name: 'Wspólnoty wiejskie',
    desc: 'Drobny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['set_core_n'],
    baseCost: { wood: 140, clay: 170, iron: 170 },
    costFactor: 1.28,
    effect: { kind: 'pop_mult', perLevel: 0.02 },
  },
  set_core_m4: {
    id: 'set_core_m4',
    name: 'Płodozmian',
    desc: 'Wyraźny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['set_core_n'],
    baseCost: { wood: 160, clay: 200, iron: 200 },
    costFactor: 1.3,
    effect: { kind: 'pop_mult', perLevel: 0.025 },
  },

  // --- set_deep: rozległe osadnictwo -----------------------------------
  set_deep_n: {
    id: 'set_deep_n',
    name: 'Rozległe pola',
    desc: 'Notable osadnictwa: duży wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_deep',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['set_core_n'],
    baseCost: { wood: 1100, clay: 1400, iron: 1400 },
    costFactor: 1.55,
    effect: { kind: 'pop_mult', perLevel: 0.08 },
  },
  set_deep_m1: {
    id: 'set_deep_m1',
    name: 'Sady i ogrody',
    desc: 'Wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['set_deep_n'],
    baseCost: { wood: 400, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'pop_mult', perLevel: 0.02 },
  },
  set_deep_m2: {
    id: 'set_deep_m2',
    name: 'Pastwiska',
    desc: 'Wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['set_deep_n'],
    baseCost: { wood: 440, clay: 550, iron: 550 },
    costFactor: 1.32,
    effect: { kind: 'pop_mult', perLevel: 0.02 },
  },
  set_deep_m3: {
    id: 'set_deep_m3',
    name: 'Młyny zbożowe',
    desc: 'Wyraźny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['set_deep_m1'],
    baseCost: { wood: 480, clay: 600, iron: 600 },
    costFactor: 1.33,
    effect: { kind: 'pop_mult', perLevel: 0.025 },
  },
  set_deep_m4: {
    id: 'set_deep_m4',
    name: 'Spichrze wiejskie',
    desc: 'Marginalny, głęboki wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_deep',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['set_deep_m2'],
    baseCost: { wood: 360, clay: 460, iron: 460 },
    costFactor: 1.3,
    effect: { kind: 'pop_mult', perLevel: 0.012 },
  },
  set_deep_m5: {
    id: 'set_deep_m5',
    name: 'Drogi osadnicze',
    desc: 'Wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['set_deep_n'],
    baseCost: { wood: 440, clay: 550, iron: 550 },
    costFactor: 1.32,
    effect: { kind: 'pop_mult', perLevel: 0.02 },
  },

  // --- set_master: gateway + szczyt osadnictwa -------------------------
  set_gateway: {
    id: 'set_gateway',
    name: 'Wielkie migracje',
    desc: 'Brama osadnictwa (drogie, jednorazowe): trwały wzrost limitu populacji. Odsłania szczytowy klaster osadniczy.',
    category: 'settlement',
    cluster: 'set_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['set_deep_n'],
    baseCost: { wood: 6000, clay: 7000, iron: 7000 },
    costFactor: 1.0,
    effect: { kind: 'pop_mult', perLevel: 0.05 },
  },
  set_master_n: {
    id: 'set_master_n',
    name: 'Kwitnące prowincje',
    desc: 'Szczytowy notable osadnictwa: bardzo duży wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_master',
    archetype: 'notable',
    maxLevel: 3,
    prerequisites: ['set_gateway'],
    baseCost: { wood: 4000, clay: 5000, iron: 5000 },
    costFactor: 1.6,
    effect: { kind: 'pop_mult', perLevel: 0.1 },
  },
  set_master_m1: {
    id: 'set_master_m1',
    name: 'Miasta targowe',
    desc: 'Znaczny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_master',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['set_master_n'],
    baseCost: { wood: 1800, clay: 2200, iron: 2200 },
    costFactor: 1.35,
    effect: { kind: 'pop_mult', perLevel: 0.025 },
  },
  set_master_m2: {
    id: 'set_master_m2',
    name: 'Kolonie',
    desc: 'Znaczny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_master',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['set_master_n'],
    baseCost: { wood: 1900, clay: 2400, iron: 2400 },
    costFactor: 1.35,
    effect: { kind: 'pop_mult', perLevel: 0.025 },
  },
  set_master_m3: {
    id: 'set_master_m3',
    name: 'Wielkie rody',
    desc: 'Silny wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['set_master_m1'],
    baseCost: { wood: 2100, clay: 2600, iron: 2600 },
    costFactor: 1.36,
    effect: { kind: 'pop_mult', perLevel: 0.03 },
  },
  set_master_m4: {
    id: 'set_master_m4',
    name: 'Prawo osadnicze',
    desc: 'Marginalny, głęboki wzrost limitu populacji.',
    category: 'settlement',
    cluster: 'set_master',
    archetype: 'minor',
    maxLevel: 10,
    prerequisites: ['set_master_m2'],
    baseCost: { wood: 1600, clay: 2000, iron: 2000 },
    costFactor: 1.33,
    effect: { kind: 'pop_mult', perLevel: 0.015 },
  },

  // =====================================================================
  // MILITARY arm — attack_mult (army attack power)
  // 3 clusters (mil_core / mil_deep / mil_master), 18 nodes, 1 gateway.
  // =====================================================================

  // --- mil_core: entry cluster -----------------------------------------
  mil_root: {
    id: 'mil_root',
    name: 'Wojsko',
    desc: 'Wejście do gałęzi wojskowej. Niewielki wzrost siły ataku armii na poziom.',
    category: 'military',
    cluster: 'mil_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 140, clay: 140, iron: 140 },
    costFactor: 1.28,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_core_n: {
    id: 'mil_core_n',
    name: 'Wyszkoleni wojownicy',
    desc: 'Notable wojska: znaczny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_core',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['mil_root'],
    baseCost: { wood: 420, clay: 420, iron: 420 },
    costFactor: 1.5,
    effect: { kind: 'attack_mult', perLevel: 0.03 },
  },
  mil_core_m1: {
    id: 'mil_core_m1',
    name: 'Ostre głownie',
    desc: 'Drobny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['mil_root'],
    baseCost: { wood: 170, clay: 170, iron: 170 },
    costFactor: 1.3,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_core_m2: {
    id: 'mil_core_m2',
    name: 'Włócznie bojowe',
    desc: 'Drobny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_root'],
    baseCost: { wood: 175, clay: 175, iron: 175 },
    costFactor: 1.3,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_core_m3: {
    id: 'mil_core_m3',
    name: 'Topory wojenne',
    desc: 'Drobny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_core_n'],
    baseCost: { wood: 180, clay: 180, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_core_m4: {
    id: 'mil_core_m4',
    name: 'Zaprawa bojowa',
    desc: 'Drobny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['mil_core_n'],
    baseCost: { wood: 185, clay: 185, iron: 185 },
    costFactor: 1.3,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },

  // --- mil_deep: zaprawieni w boju -------------------------------------
  mil_deep_n: {
    id: 'mil_deep_n',
    name: 'Hartowani w boju',
    desc: 'Notable wojska: duży wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_deep',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['mil_core_n'],
    baseCost: { wood: 1300, clay: 1300, iron: 1300 },
    costFactor: 1.5,
    effect: { kind: 'attack_mult', perLevel: 0.03 },
  },
  mil_deep_m1: {
    id: 'mil_deep_m1',
    name: 'Kuźnie wojenne',
    desc: 'Wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['mil_deep_n'],
    baseCost: { wood: 480, clay: 480, iron: 480 },
    costFactor: 1.32,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_deep_m2: {
    id: 'mil_deep_m2',
    name: 'Bojowy zapał',
    desc: 'Wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_deep_m3: {
    id: 'mil_deep_m3',
    name: 'Taktyka szturmu',
    desc: 'Wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_deep_m1'],
    baseCost: { wood: 520, clay: 520, iron: 520 },
    costFactor: 1.32,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_deep_m4: {
    id: 'mil_deep_m4',
    name: 'Doborowe oddziały',
    desc: 'Wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['mil_deep_m2'],
    baseCost: { wood: 540, clay: 540, iron: 540 },
    costFactor: 1.32,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_deep_m5: {
    id: 'mil_deep_m5',
    name: 'Sztuka oblężnicza',
    desc: 'Wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['mil_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },

  // --- mil_master: gateway + szczyt wojska -----------------------------
  mil_gateway: {
    id: 'mil_gateway',
    name: 'Wielka mobilizacja',
    desc: 'Brama wojska (drogie, jednorazowe): trwały wzrost siły ataku armii. Odsłania szczytowy klaster wojskowy.',
    category: 'military',
    cluster: 'mil_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['mil_deep_n'],
    baseCost: { wood: 7000, clay: 7000, iron: 7000 },
    costFactor: 1.0,
    effect: { kind: 'attack_mult', perLevel: 0.03 },
  },
  mil_master_n: {
    id: 'mil_master_n',
    name: 'Niezwyciężona armia',
    desc: 'Szczytowy notable wojska: bardzo duży wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_master',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['mil_gateway'],
    baseCost: { wood: 5000, clay: 5000, iron: 5000 },
    costFactor: 1.55,
    effect: { kind: 'attack_mult', perLevel: 0.04 },
  },
  mil_master_m1: {
    id: 'mil_master_m1',
    name: 'Mistrzowie miecza',
    desc: 'Znaczny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_master_n'],
    baseCost: { wood: 2200, clay: 2200, iron: 2200 },
    costFactor: 1.35,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_master_m2: {
    id: 'mil_master_m2',
    name: 'Gwardia przyboczna',
    desc: 'Znaczny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_master_n'],
    baseCost: { wood: 2300, clay: 2300, iron: 2300 },
    costFactor: 1.35,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_master_m3: {
    id: 'mil_master_m3',
    name: 'Sztandary chwały',
    desc: 'Znaczny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_master_m1'],
    baseCost: { wood: 2400, clay: 2400, iron: 2400 },
    costFactor: 1.35,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },
  mil_master_m4: {
    id: 'mil_master_m4',
    name: 'Krwawa furia',
    desc: 'Znaczny wzrost siły ataku armii.',
    category: 'military',
    cluster: 'mil_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['mil_master_m2'],
    baseCost: { wood: 2100, clay: 2100, iron: 2100 },
    costFactor: 1.35,
    effect: { kind: 'attack_mult', perLevel: 0.005 },
  },

  // =====================================================================
  // FORTIFICATION arm — defense_mult (army defence power)
  // 3 clusters (fort_core / fort_deep / fort_master), 18 nodes, 1 gateway.
  // =====================================================================

  // --- fort_core: entry cluster ----------------------------------------
  fort_root: {
    id: 'fort_root',
    name: 'Fortyfikacje',
    desc: 'Wejście do gałęzi obronnej. Niewielki wzrost siły obrony armii na poziom.',
    category: 'fortification',
    cluster: 'fort_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 140, clay: 140, iron: 140 },
    costFactor: 1.28,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_core_n: {
    id: 'fort_core_n',
    name: 'Mocne palisady',
    desc: 'Notable fortyfikacji: znaczny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_core',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['fort_root'],
    baseCost: { wood: 420, clay: 420, iron: 420 },
    costFactor: 1.5,
    effect: { kind: 'defense_mult', perLevel: 0.03 },
  },
  fort_core_m1: {
    id: 'fort_core_m1',
    name: 'Wały ziemne',
    desc: 'Drobny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['fort_root'],
    baseCost: { wood: 170, clay: 170, iron: 170 },
    costFactor: 1.3,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_core_m2: {
    id: 'fort_core_m2',
    name: 'Rowy obronne',
    desc: 'Drobny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_root'],
    baseCost: { wood: 175, clay: 175, iron: 175 },
    costFactor: 1.3,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_core_m3: {
    id: 'fort_core_m3',
    name: 'Zasieki',
    desc: 'Drobny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_core_n'],
    baseCost: { wood: 180, clay: 180, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_core_m4: {
    id: 'fort_core_m4',
    name: 'Czujne straże',
    desc: 'Drobny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['fort_core_n'],
    baseCost: { wood: 185, clay: 185, iron: 185 },
    costFactor: 1.3,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },

  // --- fort_deep: warownie --------------------------------------------
  fort_deep_n: {
    id: 'fort_deep_n',
    name: 'Kamienne mury',
    desc: 'Notable fortyfikacji: duży wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_deep',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['fort_core_n'],
    baseCost: { wood: 1300, clay: 1300, iron: 1300 },
    costFactor: 1.5,
    effect: { kind: 'defense_mult', perLevel: 0.03 },
  },
  fort_deep_m1: {
    id: 'fort_deep_m1',
    name: 'Baszty',
    desc: 'Wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['fort_deep_n'],
    baseCost: { wood: 480, clay: 480, iron: 480 },
    costFactor: 1.32,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_deep_m2: {
    id: 'fort_deep_m2',
    name: 'Blanki',
    desc: 'Wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_deep_m3: {
    id: 'fort_deep_m3',
    name: 'Bramy warowne',
    desc: 'Wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_deep_m1'],
    baseCost: { wood: 520, clay: 520, iron: 520 },
    costFactor: 1.32,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_deep_m4: {
    id: 'fort_deep_m4',
    name: 'Głębokie fosy',
    desc: 'Wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['fort_deep_m2'],
    baseCost: { wood: 540, clay: 540, iron: 540 },
    costFactor: 1.32,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_deep_m5: {
    id: 'fort_deep_m5',
    name: 'Machikuły',
    desc: 'Wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['fort_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },

  // --- fort_master: gateway + szczyt fortyfikacji ----------------------
  fort_gateway: {
    id: 'fort_gateway',
    name: 'Wielka twierdza',
    desc: 'Brama fortyfikacji (drogie, jednorazowe): trwały wzrost siły obrony armii. Odsłania szczytowy klaster obronny.',
    category: 'fortification',
    cluster: 'fort_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['fort_deep_n'],
    baseCost: { wood: 7000, clay: 7000, iron: 7000 },
    costFactor: 1.0,
    effect: { kind: 'defense_mult', perLevel: 0.03 },
  },
  fort_master_n: {
    id: 'fort_master_n',
    name: 'Niezdobyta cytadela',
    desc: 'Szczytowy notable fortyfikacji: bardzo duży wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_master',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['fort_gateway'],
    baseCost: { wood: 5000, clay: 5000, iron: 5000 },
    costFactor: 1.55,
    effect: { kind: 'defense_mult', perLevel: 0.04 },
  },
  fort_master_m1: {
    id: 'fort_master_m1',
    name: 'Podwójne mury',
    desc: 'Znaczny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_master_n'],
    baseCost: { wood: 2200, clay: 2200, iron: 2200 },
    costFactor: 1.35,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_master_m2: {
    id: 'fort_master_m2',
    name: 'Wieże obronne',
    desc: 'Znaczny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_master_n'],
    baseCost: { wood: 2300, clay: 2300, iron: 2300 },
    costFactor: 1.35,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_master_m3: {
    id: 'fort_master_m3',
    name: 'Barbakan',
    desc: 'Znaczny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_master_m1'],
    baseCost: { wood: 2400, clay: 2400, iron: 2400 },
    costFactor: 1.35,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },
  fort_master_m4: {
    id: 'fort_master_m4',
    name: 'Wieczna straż',
    desc: 'Znaczny wzrost siły obrony armii.',
    category: 'fortification',
    cluster: 'fort_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['fort_master_m2'],
    baseCost: { wood: 2100, clay: 2100, iron: 2100 },
    costFactor: 1.35,
    effect: { kind: 'defense_mult', perLevel: 0.005 },
  },

  // =====================================================================
  // LOGISTICS arm — march_speed (fraction off march time)
  // 3 clusters (log_core / log_deep / log_master), 18 nodes, 1 gateway.
  // =====================================================================

  // --- log_core: entry cluster -----------------------------------------
  log_root: {
    id: 'log_root',
    name: 'Logistyka',
    desc: 'Wejście do gałęzi logistycznej. Niewielkie skrócenie czasu marszu na poziom.',
    category: 'logistics',
    cluster: 'log_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 140, clay: 140, iron: 140 },
    costFactor: 1.28,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_core_n: {
    id: 'log_core_n',
    name: 'Utwardzone trakty',
    desc: 'Notable logistyki: znaczne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_core',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['log_root'],
    baseCost: { wood: 420, clay: 420, iron: 420 },
    costFactor: 1.5,
    effect: { kind: 'march_speed', perLevel: 0.03 },
  },
  log_core_m1: {
    id: 'log_core_m1',
    name: 'Mapy szlaków',
    desc: 'Drobne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['log_root'],
    baseCost: { wood: 170, clay: 170, iron: 170 },
    costFactor: 1.3,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_core_m2: {
    id: 'log_core_m2',
    name: 'Lekki ekwipunek',
    desc: 'Drobne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_root'],
    baseCost: { wood: 175, clay: 175, iron: 175 },
    costFactor: 1.3,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_core_m3: {
    id: 'log_core_m3',
    name: 'Zwiadowcy',
    desc: 'Drobne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_core_n'],
    baseCost: { wood: 180, clay: 180, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_core_m4: {
    id: 'log_core_m4',
    name: 'Forsowny marsz',
    desc: 'Drobne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['log_core_n'],
    baseCost: { wood: 185, clay: 185, iron: 185 },
    costFactor: 1.3,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },

  // --- log_deep: sieć dróg --------------------------------------------
  log_deep_n: {
    id: 'log_deep_n',
    name: 'Sieć dróg',
    desc: 'Notable logistyki: duże skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_deep',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['log_core_n'],
    baseCost: { wood: 1300, clay: 1300, iron: 1300 },
    costFactor: 1.5,
    effect: { kind: 'march_speed', perLevel: 0.03 },
  },
  log_deep_m1: {
    id: 'log_deep_m1',
    name: 'Mosty i przeprawy',
    desc: 'Skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['log_deep_n'],
    baseCost: { wood: 480, clay: 480, iron: 480 },
    costFactor: 1.32,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_deep_m2: {
    id: 'log_deep_m2',
    name: 'Stacje postojowe',
    desc: 'Skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_deep_m3: {
    id: 'log_deep_m3',
    name: 'Tabory zaopatrzenia',
    desc: 'Skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_deep_m1'],
    baseCost: { wood: 520, clay: 520, iron: 520 },
    costFactor: 1.32,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_deep_m4: {
    id: 'log_deep_m4',
    name: 'Konni posłańcy',
    desc: 'Skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['log_deep_m2'],
    baseCost: { wood: 540, clay: 540, iron: 540 },
    costFactor: 1.32,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_deep_m5: {
    id: 'log_deep_m5',
    name: 'Doświadczeni przewodnicy',
    desc: 'Skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['log_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },

  // --- log_master: gateway + szczyt logistyki --------------------------
  log_gateway: {
    id: 'log_gateway',
    name: 'Cesarskie gościńce',
    desc: 'Brama logistyki (drogie, jednorazowe): trwałe skrócenie czasu marszu. Odsłania szczytowy klaster logistyczny.',
    category: 'logistics',
    cluster: 'log_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['log_deep_n'],
    baseCost: { wood: 7000, clay: 7000, iron: 7000 },
    costFactor: 1.0,
    effect: { kind: 'march_speed', perLevel: 0.03 },
  },
  log_master_n: {
    id: 'log_master_n',
    name: 'Błyskawiczne marsze',
    desc: 'Szczytowy notable logistyki: bardzo duże skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_master',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['log_gateway'],
    baseCost: { wood: 5000, clay: 5000, iron: 5000 },
    costFactor: 1.55,
    effect: { kind: 'march_speed', perLevel: 0.04 },
  },
  log_master_m1: {
    id: 'log_master_m1',
    name: 'Kurierzy',
    desc: 'Znaczne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_master_n'],
    baseCost: { wood: 2200, clay: 2200, iron: 2200 },
    costFactor: 1.35,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_master_m2: {
    id: 'log_master_m2',
    name: 'Zmiana koni',
    desc: 'Znaczne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_master_n'],
    baseCost: { wood: 2300, clay: 2300, iron: 2300 },
    costFactor: 1.35,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_master_m3: {
    id: 'log_master_m3',
    name: 'Marsz nocny',
    desc: 'Znaczne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_master_m1'],
    baseCost: { wood: 2400, clay: 2400, iron: 2400 },
    costFactor: 1.35,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },
  log_master_m4: {
    id: 'log_master_m4',
    name: 'Żelazna dyscyplina',
    desc: 'Znaczne skrócenie czasu marszu.',
    category: 'logistics',
    cluster: 'log_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['log_master_m2'],
    baseCost: { wood: 2100, clay: 2100, iron: 2100 },
    costFactor: 1.35,
    effect: { kind: 'march_speed', perLevel: 0.005 },
  },

  // =====================================================================
  // PLUNDER arm — loot_mult (loot hauled from a target)
  // 3 clusters (plun_core / plun_deep / plun_master), 18 nodes, 1 gateway.
  // =====================================================================

  // --- plun_core: entry cluster ----------------------------------------
  plun_root: {
    id: 'plun_root',
    name: 'Grabież',
    desc: 'Wejście do gałęzi grabieżczej. Niewielki wzrost zabieranego łupu na poziom.',
    category: 'plunder',
    cluster: 'plun_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 140, clay: 140, iron: 140 },
    costFactor: 1.28,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_core_n: {
    id: 'plun_core_n',
    name: 'Sprawni łupieżcy',
    desc: 'Notable grabieży: znaczny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_core',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['plun_root'],
    baseCost: { wood: 420, clay: 420, iron: 420 },
    costFactor: 1.5,
    effect: { kind: 'loot_mult', perLevel: 0.03 },
  },
  plun_core_m1: {
    id: 'plun_core_m1',
    name: 'Juki i sakwy',
    desc: 'Drobny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['plun_root'],
    baseCost: { wood: 170, clay: 170, iron: 170 },
    costFactor: 1.3,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_core_m2: {
    id: 'plun_core_m2',
    name: 'Wozy zdobyczne',
    desc: 'Drobny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_root'],
    baseCost: { wood: 175, clay: 175, iron: 175 },
    costFactor: 1.3,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_core_m3: {
    id: 'plun_core_m3',
    name: 'Tropiciele skarbów',
    desc: 'Drobny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_core_n'],
    baseCost: { wood: 180, clay: 180, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_core_m4: {
    id: 'plun_core_m4',
    name: 'Szybki rabunek',
    desc: 'Drobny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['plun_core_n'],
    baseCost: { wood: 185, clay: 185, iron: 185 },
    costFactor: 1.3,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },

  // --- plun_deep: mistrzowie grabieży ----------------------------------
  plun_deep_n: {
    id: 'plun_deep_n',
    name: 'Mistrzowie grabieży',
    desc: 'Notable grabieży: duży wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_deep',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['plun_core_n'],
    baseCost: { wood: 1300, clay: 1300, iron: 1300 },
    costFactor: 1.5,
    effect: { kind: 'loot_mult', perLevel: 0.03 },
  },
  plun_deep_m1: {
    id: 'plun_deep_m1',
    name: 'Objuczone konie',
    desc: 'Wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['plun_deep_n'],
    baseCost: { wood: 480, clay: 480, iron: 480 },
    costFactor: 1.32,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_deep_m2: {
    id: 'plun_deep_m2',
    name: 'Ukryte schowki',
    desc: 'Wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_deep_m3: {
    id: 'plun_deep_m3',
    name: 'Plądrowanie spichlerzy',
    desc: 'Wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_deep_m1'],
    baseCost: { wood: 520, clay: 520, iron: 520 },
    costFactor: 1.32,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_deep_m4: {
    id: 'plun_deep_m4',
    name: 'Łupieżcze szlaki',
    desc: 'Wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['plun_deep_m2'],
    baseCost: { wood: 540, clay: 540, iron: 540 },
    costFactor: 1.32,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_deep_m5: {
    id: 'plun_deep_m5',
    name: 'Doświadczeni rabusie',
    desc: 'Wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['plun_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },

  // --- plun_master: gateway + szczyt grabieży --------------------------
  plun_gateway: {
    id: 'plun_gateway',
    name: 'Wielki najazd',
    desc: 'Brama grabieży (drogie, jednorazowe): trwały wzrost zabieranego łupu. Odsłania szczytowy klaster grabieżczy.',
    category: 'plunder',
    cluster: 'plun_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['plun_deep_n'],
    baseCost: { wood: 7000, clay: 7000, iron: 7000 },
    costFactor: 1.0,
    effect: { kind: 'loot_mult', perLevel: 0.03 },
  },
  plun_master_n: {
    id: 'plun_master_n',
    name: 'Bezlitosne hordy',
    desc: 'Szczytowy notable grabieży: bardzo duży wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_master',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['plun_gateway'],
    baseCost: { wood: 5000, clay: 5000, iron: 5000 },
    costFactor: 1.55,
    effect: { kind: 'loot_mult', perLevel: 0.04 },
  },
  plun_master_m1: {
    id: 'plun_master_m1',
    name: 'Karawany zdobyczy',
    desc: 'Znaczny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_master_n'],
    baseCost: { wood: 2200, clay: 2200, iron: 2200 },
    costFactor: 1.35,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_master_m2: {
    id: 'plun_master_m2',
    name: 'Daniny i okup',
    desc: 'Znaczny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_master_n'],
    baseCost: { wood: 2300, clay: 2300, iron: 2300 },
    costFactor: 1.35,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_master_m3: {
    id: 'plun_master_m3',
    name: 'Spustoszenie',
    desc: 'Znaczny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_master_m1'],
    baseCost: { wood: 2400, clay: 2400, iron: 2400 },
    costFactor: 1.35,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },
  plun_master_m4: {
    id: 'plun_master_m4',
    name: 'Złote żniwa',
    desc: 'Znaczny wzrost zabieranego łupu.',
    category: 'plunder',
    cluster: 'plun_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['plun_master_m2'],
    baseCost: { wood: 2100, clay: 2100, iron: 2100 },
    costFactor: 1.35,
    effect: { kind: 'loot_mult', perLevel: 0.005 },
  },

  // =====================================================================
  // CONSTRUCTION arm — cost_reduction (fraction off building cost)
  // 3 clusters (con_core / con_deep / con_master), 18 nodes, 1 gateway.
  // =====================================================================

  // --- con_core: entry cluster -----------------------------------------
  con_root: {
    id: 'con_root',
    name: 'Budownictwo',
    desc: 'Wejście do gałęzi budowlanej. Niewielka zniżka kosztu budowy na poziom.',
    category: 'construction',
    cluster: 'con_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 140, clay: 140, iron: 140 },
    costFactor: 1.28,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_core_n: {
    id: 'con_core_n',
    name: 'Sprawni budowniczy',
    desc: 'Notable budownictwa: znaczna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_core',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['con_root'],
    baseCost: { wood: 420, clay: 420, iron: 420 },
    costFactor: 1.5,
    effect: { kind: 'cost_reduction', perLevel: 0.03 },
  },
  con_core_m1: {
    id: 'con_core_m1',
    name: 'Rusztowania',
    desc: 'Drobna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['con_root'],
    baseCost: { wood: 170, clay: 170, iron: 170 },
    costFactor: 1.3,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_core_m2: {
    id: 'con_core_m2',
    name: 'Sprawdzone plany',
    desc: 'Drobna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_root'],
    baseCost: { wood: 175, clay: 175, iron: 175 },
    costFactor: 1.3,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_core_m3: {
    id: 'con_core_m3',
    name: 'Tania cegła',
    desc: 'Drobna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_core_n'],
    baseCost: { wood: 180, clay: 180, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_core_m4: {
    id: 'con_core_m4',
    name: 'Dźwigi i wciągi',
    desc: 'Drobna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['con_core_n'],
    baseCost: { wood: 185, clay: 185, iron: 185 },
    costFactor: 1.3,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },

  // --- con_deep: gildia murarzy ---------------------------------------
  con_deep_n: {
    id: 'con_deep_n',
    name: 'Gildia murarzy',
    desc: 'Notable budownictwa: duża zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_deep',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['con_core_n'],
    baseCost: { wood: 1300, clay: 1300, iron: 1300 },
    costFactor: 1.5,
    effect: { kind: 'cost_reduction', perLevel: 0.03 },
  },
  con_deep_m1: {
    id: 'con_deep_m1',
    name: 'Prefabrykaty',
    desc: 'Zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['con_deep_n'],
    baseCost: { wood: 480, clay: 480, iron: 480 },
    costFactor: 1.32,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_deep_m2: {
    id: 'con_deep_m2',
    name: 'Wydajne warsztaty',
    desc: 'Zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_deep_m3: {
    id: 'con_deep_m3',
    name: 'Gospodarka materiałem',
    desc: 'Zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_deep_m1'],
    baseCost: { wood: 520, clay: 520, iron: 520 },
    costFactor: 1.32,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_deep_m4: {
    id: 'con_deep_m4',
    name: 'Doświadczeni majstrowie',
    desc: 'Zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['con_deep_m2'],
    baseCost: { wood: 540, clay: 540, iron: 540 },
    costFactor: 1.32,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_deep_m5: {
    id: 'con_deep_m5',
    name: 'Lokalne kamieniołomy',
    desc: 'Zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['con_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },

  // --- con_master: gateway + szczyt budownictwa ------------------------
  con_gateway: {
    id: 'con_gateway',
    name: 'Wielkie place budowy',
    desc: 'Brama budownictwa (drogie, jednorazowe): trwała zniżka kosztu budowy. Odsłania szczytowy klaster budowlany.',
    category: 'construction',
    cluster: 'con_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['con_deep_n'],
    baseCost: { wood: 7000, clay: 7000, iron: 7000 },
    costFactor: 1.0,
    effect: { kind: 'cost_reduction', perLevel: 0.03 },
  },
  con_master_n: {
    id: 'con_master_n',
    name: 'Mistrzowie architektury',
    desc: 'Szczytowy notable budownictwa: bardzo duża zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_master',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['con_gateway'],
    baseCost: { wood: 5000, clay: 5000, iron: 5000 },
    costFactor: 1.55,
    effect: { kind: 'cost_reduction', perLevel: 0.04 },
  },
  con_master_m1: {
    id: 'con_master_m1',
    name: 'Inżynierowie',
    desc: 'Znaczna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_master_n'],
    baseCost: { wood: 2200, clay: 2200, iron: 2200 },
    costFactor: 1.35,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_master_m2: {
    id: 'con_master_m2',
    name: 'Maszyny budowlane',
    desc: 'Znaczna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_master_n'],
    baseCost: { wood: 2300, clay: 2300, iron: 2300 },
    costFactor: 1.35,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_master_m3: {
    id: 'con_master_m3',
    name: 'Hurtowy surowiec',
    desc: 'Znaczna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_master_m1'],
    baseCost: { wood: 2400, clay: 2400, iron: 2400 },
    costFactor: 1.35,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },
  con_master_m4: {
    id: 'con_master_m4',
    name: 'Doskonała organizacja',
    desc: 'Znaczna zniżka kosztu budowy.',
    category: 'construction',
    cluster: 'con_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['con_master_m2'],
    baseCost: { wood: 2100, clay: 2100, iron: 2100 },
    costFactor: 1.35,
    effect: { kind: 'cost_reduction', perLevel: 0.005 },
  },

  // =====================================================================
  // TRAINING arm — recruit_speed (fraction off recruitment time)
  // 3 clusters (tra_core / tra_deep / tra_master), 18 nodes, 1 gateway.
  // =====================================================================

  // --- tra_core: entry cluster -----------------------------------------
  tra_root: {
    id: 'tra_root',
    name: 'Szkolenie',
    desc: 'Wejście do gałęzi szkoleniowej. Niewielkie skrócenie czasu rekrutacji na poziom.',
    category: 'training',
    cluster: 'tra_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: [],
    baseCost: { wood: 140, clay: 140, iron: 140 },
    costFactor: 1.28,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_core_n: {
    id: 'tra_core_n',
    name: 'Sprawni instruktorzy',
    desc: 'Notable szkolenia: znaczne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_core',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['tra_root'],
    baseCost: { wood: 420, clay: 420, iron: 420 },
    costFactor: 1.5,
    effect: { kind: 'recruit_speed', perLevel: 0.03 },
  },
  tra_core_m1: {
    id: 'tra_core_m1',
    name: 'Place ćwiczeń',
    desc: 'Drobne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['tra_root'],
    baseCost: { wood: 170, clay: 170, iron: 170 },
    costFactor: 1.3,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_core_m2: {
    id: 'tra_core_m2',
    name: 'Standardowy dryl',
    desc: 'Drobne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_root'],
    baseCost: { wood: 175, clay: 175, iron: 175 },
    costFactor: 1.3,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_core_m3: {
    id: 'tra_core_m3',
    name: 'Sierżanci szkoleniowi',
    desc: 'Drobne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_core',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_core_n'],
    baseCost: { wood: 180, clay: 180, iron: 180 },
    costFactor: 1.3,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_core_m4: {
    id: 'tra_core_m4',
    name: 'Gotowy ekwipunek',
    desc: 'Drobne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_core',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['tra_core_n'],
    baseCost: { wood: 185, clay: 185, iron: 185 },
    costFactor: 1.3,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },

  // --- tra_deep: koszary ----------------------------------------------
  tra_deep_n: {
    id: 'tra_deep_n',
    name: 'Koszary szkoleniowe',
    desc: 'Notable szkolenia: duże skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_deep',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['tra_core_n'],
    baseCost: { wood: 1300, clay: 1300, iron: 1300 },
    costFactor: 1.5,
    effect: { kind: 'recruit_speed', perLevel: 0.03 },
  },
  tra_deep_m1: {
    id: 'tra_deep_m1',
    name: 'Obozy rekruckie',
    desc: 'Skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['tra_deep_n'],
    baseCost: { wood: 480, clay: 480, iron: 480 },
    costFactor: 1.32,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_deep_m2: {
    id: 'tra_deep_m2',
    name: 'Doświadczeni weterani',
    desc: 'Skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_deep_m3: {
    id: 'tra_deep_m3',
    name: 'Szybki nabór',
    desc: 'Skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_deep',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_deep_m1'],
    baseCost: { wood: 520, clay: 520, iron: 520 },
    costFactor: 1.32,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_deep_m4: {
    id: 'tra_deep_m4',
    name: 'Zaprawa polowa',
    desc: 'Skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['tra_deep_m2'],
    baseCost: { wood: 540, clay: 540, iron: 540 },
    costFactor: 1.32,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_deep_m5: {
    id: 'tra_deep_m5',
    name: 'Podoficerowie',
    desc: 'Skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_deep',
    archetype: 'minor',
    maxLevel: 8,
    prerequisites: ['tra_deep_n'],
    baseCost: { wood: 500, clay: 500, iron: 500 },
    costFactor: 1.32,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },

  // --- tra_master: gateway + szczyt szkolenia --------------------------
  tra_gateway: {
    id: 'tra_gateway',
    name: 'Powszechny pobór',
    desc: 'Brama szkolenia (drogie, jednorazowe): trwałe skrócenie czasu rekrutacji. Odsłania szczytowy klaster szkoleniowy.',
    category: 'training',
    cluster: 'tra_master',
    archetype: 'gateway',
    maxLevel: 1,
    prerequisites: ['tra_deep_n'],
    baseCost: { wood: 7000, clay: 7000, iron: 7000 },
    costFactor: 1.0,
    effect: { kind: 'recruit_speed', perLevel: 0.03 },
  },
  tra_master_n: {
    id: 'tra_master_n',
    name: 'Akademia wojskowa',
    desc: 'Szczytowy notable szkolenia: bardzo duże skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_master',
    archetype: 'notable',
    maxLevel: 2,
    prerequisites: ['tra_gateway'],
    baseCost: { wood: 5000, clay: 5000, iron: 5000 },
    costFactor: 1.55,
    effect: { kind: 'recruit_speed', perLevel: 0.04 },
  },
  tra_master_m1: {
    id: 'tra_master_m1',
    name: 'Mistrzowie musztry',
    desc: 'Znaczne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_master_n'],
    baseCost: { wood: 2200, clay: 2200, iron: 2200 },
    costFactor: 1.35,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_master_m2: {
    id: 'tra_master_m2',
    name: 'Linie szkoleniowe',
    desc: 'Znaczne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_master_n'],
    baseCost: { wood: 2300, clay: 2300, iron: 2300 },
    costFactor: 1.35,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_master_m3: {
    id: 'tra_master_m3',
    name: 'Elitarny dryl',
    desc: 'Znaczne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_master_m1'],
    baseCost: { wood: 2400, clay: 2400, iron: 2400 },
    costFactor: 1.35,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
  tra_master_m4: {
    id: 'tra_master_m4',
    name: 'Stała gotowość',
    desc: 'Znaczne skrócenie czasu rekrutacji.',
    category: 'training',
    cluster: 'tra_master',
    archetype: 'minor',
    maxLevel: 7,
    prerequisites: ['tra_master_m2'],
    baseCost: { wood: 2100, clay: 2100, iron: 2100 },
    costFactor: 1.35,
    effect: { kind: 'recruit_speed', perLevel: 0.005 },
  },
}

/**
 * Stable iteration order over {@link TECH_NODES}. Derived from the data so it stays
 * deterministic (Object key order here = source order), driving every order-sensitive
 * pass: aggregateTechMods, layout, validation, the sim. Keep source order stable when
 * extending (append new nodes) so saves/round-trips stay reproducible.
 */
export const TECH_NODE_IDS: readonly string[] = Object.keys(TECH_NODES)

/**
 * Roots = nodes with no prerequisites (always available). Derived deterministically
 * from {@link TECH_NODE_IDS} so adding a node is a single data edit. The contract:
 * exactly one entry per category — the 9 `*_root` nodes (eco/sto/set + the M3.2 arms
 * mil/fort/log/plun/con/tra).
 */
export const TECH_ROOTS: readonly string[] = TECH_NODE_IDS.filter(
  (id) => TECH_NODES[id].prerequisites.length === 0,
)
